# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocat < Formula
  desc "A simple CLI for managing your tasks."
  homepage "https://github.com/sho0pi/gocat"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sho0pi/gocat/releases/download/v0.0.1/gocat_0.0.1_darwin_amd64.tar.gz"
      sha256 "9252448376382ea6c2aae8eee9024309acbb094eb150fb59398d272dc8f76063"

      def install
        bin.install "gocat"
        bash_completion.install "completions/gocat.bash" => "gocat"
        zsh_completion.install "completions/gocat.zsh" => "_gocat"
        fish_completion.install "completions/gocat.fish" => "gocat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sho0pi/gocat/releases/download/v0.0.1/gocat_0.0.1_darwin_arm64.tar.gz"
      sha256 "63a9fee692d70fb7eac46e65c216ea7787c58b97136543da896e7416fb9557a6"

      def install
        bin.install "gocat"
        bash_completion.install "completions/gocat.bash" => "gocat"
        zsh_completion.install "completions/gocat.zsh" => "_gocat"
        fish_completion.install "completions/gocat.fish" => "gocat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/gocat/releases/download/v0.0.1/gocat_0.0.1_linux_amd64.tar.gz"
        sha256 "2cee0c7168f4b9ca8eb65e2b956a5870e2e2af04c61a2a94fa536ee9db2c2ef1"

        def install
          bin.install "gocat"
          bash_completion.install "completions/gocat.bash" => "gocat"
          zsh_completion.install "completions/gocat.zsh" => "_gocat"
          fish_completion.install "completions/gocat.fish" => "gocat.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/gocat/releases/download/v0.0.1/gocat_0.0.1_linux_arm64.tar.gz"
        sha256 "f311db8dc6ae9fd4165fd2b3a25b902db753252b3210bee836252a2c4d52b368"

        def install
          bin.install "gocat"
          bash_completion.install "completions/gocat.bash" => "gocat"
          zsh_completion.install "completions/gocat.zsh" => "_gocat"
          fish_completion.install "completions/gocat.fish" => "gocat.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/gocat --version"
  end
end
