# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocat < Formula
  desc "A simple CLI for managing your tasks."
  homepage "https://github.com/sho0pi/gocat"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sho0pi/gocat/releases/download/v0.1.0/gocat_0.1.0_darwin_amd64.tar.gz"
      sha256 "abfb167c63cb0775fa7c39618b0b2e1c2f35602293d382c0d7cdd70fa32989b8"

      def install
        bin.install "gocat"
        bash_completion.install "completions/gocat.bash" => "gocat"
        zsh_completion.install "completions/gocat.zsh" => "_gocat"
        fish_completion.install "completions/gocat.fish" => "gocat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sho0pi/gocat/releases/download/v0.1.0/gocat_0.1.0_darwin_arm64.tar.gz"
      sha256 "487b67e2e12776d51bcd1b0a0027b955277fe6ffd11d74dd96c0b3454560f449"

      def install
        bin.install "gocat"
        bash_completion.install "completions/gocat.bash" => "gocat"
        zsh_completion.install "completions/gocat.zsh" => "_gocat"
        fish_completion.install "completions/gocat.fish" => "gocat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/gocat/releases/download/v0.1.0/gocat_0.1.0_linux_amd64.tar.gz"
        sha256 "f87b4321f65b3082be2d412218240f5201e1042541f6a0497829f2a9674a50c5"

        def install
          bin.install "gocat"
          bash_completion.install "completions/gocat.bash" => "gocat"
          zsh_completion.install "completions/gocat.zsh" => "_gocat"
          fish_completion.install "completions/gocat.fish" => "gocat.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/gocat/releases/download/v0.1.0/gocat_0.1.0_linux_arm64.tar.gz"
        sha256 "82212b213f35ee12e179d1252f0993fb2c39601c2eb3e7ad088a4f2ef6d5af1b"

        def install
          bin.install "gocat"
          bash_completion.install "completions/gocat.bash" => "gocat"
          zsh_completion.install "completions/gocat.zsh" => "_gocat"
          fish_completion.install "completions/gocat.fish" => "gocat.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/gocat --version"
  end
end
