# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickli < Formula
  desc "A simple CLI for managing your tasks."
  homepage "https://github.com/sho0pi/tickli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sho0pi/tickli/releases/download/v0.0.2/tickli_0.0.2_darwin_amd64.tar.gz"
      sha256 "0dd46e2d196d37c980d5c623372613e6b680a20e8a5a2df4beda28b4f13e258d"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sho0pi/tickli/releases/download/v0.0.2/tickli_0.0.2_darwin_arm64.tar.gz"
      sha256 "824cc5ac624dadbd2f0a52325776d01e9853845f1096b6057d66af861fe0f0de"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/v0.0.2/tickli_0.0.2_linux_amd64.tar.gz"
        sha256 "a290d2f69ffb0b5ddf38d8ca3ecd19511faa3e229230f3a820d3dd6790d1d1ad"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/v0.0.2/tickli_0.0.2_linux_arm64.tar.gz"
        sha256 "e6d302ccea1d8f23f4b87ee4202af126e00b722fdc1c71ae03a73c1448400ffa"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/tickli version"
  end
end
