# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickli < Formula
  desc "A simple CLI for managing your tasks."
  homepage "https://github.com/sho0pi/tickli"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sho0pi/tickli/releases/download/v0.0.3/tickli_0.0.3_darwin_amd64.tar.gz"
      sha256 "f1cdfa821d13775486d22ed5c96b6f7cfc82a2c3f6730c7d5223af727815f932"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sho0pi/tickli/releases/download/v0.0.3/tickli_0.0.3_darwin_arm64.tar.gz"
      sha256 "9a1342e0913884b053230db8355e2294f2a0c5699af5b5e3335ba1a691509448"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/v0.0.3/tickli_0.0.3_linux_amd64.tar.gz"
        sha256 "0e7f61eabe2412be0284684a720bcb7b553ea307419b957b2767d9afeb59bb16"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/v0.0.3/tickli_0.0.3_linux_arm64.tar.gz"
        sha256 "c56acc4df41ada1ebf9b5bb3c7eade170bb1bbb20f9574c46ba134ac3f7a61ed"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/tickli version"
  end
end
