# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickli < Formula
  desc "A simple CLI for managing your tasks."
  homepage "https://github.com/sho0pi/tickli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Sho0pi/tickli/releases/download/0.0.1/tickli_0.0.1_darwin_amd64.tar.gz"
      sha256 "b9c192566f5827ea97a0d809b893ee10a0c0236bbd422306826f34c022cb573e"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Sho0pi/tickli/releases/download/0.0.1/tickli_0.0.1_darwin_arm64.tar.gz"
      sha256 "2a68f3271ea65b31f904173c639be98522b68928fc6d9e55184ac05df95d238e"

      def install
        bin.install "tickli"
        bash_completion.install "completions/tickli.bash" => "tickli"
        zsh_completion.install "completions/tickli.zsh" => "_tickli"
        fish_completion.install "completions/tickli.fish" => "tickli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/0.0.1/tickli_0.0.1_linux_amd64.tar.gz"
        sha256 "de1d3c178a10905f4ee023af3b3f64b33fc5d6b468a9f69405b38e16b39cfa5b"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Sho0pi/tickli/releases/download/0.0.1/tickli_0.0.1_linux_arm64.tar.gz"
        sha256 "f6f6526fdcea635c1be6342460b27d66841c82680b0182986c3cafe7492a27ef"

        def install
          bin.install "tickli"
          bash_completion.install "completions/tickli.bash" => "tickli"
          zsh_completion.install "completions/tickli.zsh" => "_tickli"
          fish_completion.install "completions/tickli.fish" => "tickli.fish"
        end
      end
    end
  end
end
